title: Beaqlejs
description: "*BeaqleJS* provides a framework to create browser based listening tests and is purely based on open web standards like HTML5 and Javascript."
google_analytics: 
show_downloads: true
theme: jekyll-theme-modernist

gems:
  - jekyll-mentions
